[tox]
env_list = format, lint, type, test
no_package = true

[testenv]
dependency_groups = dev
setenv =
    PYTHONPATH = {toxinidir}
commands = pytest {posargs}

[testenv:format]
dependency_groups = dev
commands = ruff format --check .

[testenv:lint]
dependency_groups = dev
commands = ruff check .

[testenv:type]
dependency_groups = dev
commands = mypy .

[testenv:test]
dependency_groups = dev
commands = pytest {posargs}
