[tox]
env_list = lint, unit
no_package = true
min_version = 4.0.0

[testenv]
dependency_groups = dev
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/.scratch/hermes-agent
commands = pytest --import-mode=importlib {posargs}

[testenv:fmt]
dependency_groups = dev
commands = ruff format src tests

[testenv:lint]
dependency_groups = dev
commands = ruff check src tests

[testenv:unit]
dependency_groups = dev
commands =
    coverage run --branch --source=src -m pytest --import-mode=importlib {posargs}
    coverage report --show-missing --fail-under=80
    coverage xml
